### ISSUE TITLE
Outdated Alpine Linux version referenced 

### ISSUE THREAD

**Issue by alexellis** [tinkerbell/osie#1]
An outdated Alpine Linux version (3.7) is referenced in the README, and may also be in use within `osie`.

@nathangoulding it would be worth updating to harden and get the latest security patches.

I assume the built-in CI would validate that this change worked?

cc @vielmetti @gauravgahlot

**Comment by nathangoulding** [comment]
Resolved in #4. Needs testing across our fleet.

**Comment by mmlb** [comment]
Actually, https://github.com/tinkerbell/osie/pull/6
