### ISSUE TITLE
OSIE image should use multi stage builds

### ISSUE THREAD

**Issue by mmlb** [tinkerbell/osie#129]
We build a few packages from source, some of them may go away with #128 but some are likely to still be needed. Using multi stage builds would allow making better use layer caching and likely help with the final image size (#2).

**Comment by tstromberg** [comment]
@mmlb - did this land?

**Comment by mmlb** [comment]
Nope, we closed the PR until some time could be found to finish it up (https://github.com/tinkerbell/osie/pull/223). Most of the work was done already, the last bit needed was some hacking around buildx's lack of squash support.

**Comment by jacobweinstock** [comment]
Archiving repo, closing issue per [GitHub's recommendation](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories#about-repository-archival).
