### ISSUE TITLE
Unable to create ZFS file system - unsupported by kernel

### ISSUE THREAD

**Issue by anilchabba** [tinkerbell/osie#165]
ZFS files system creation support is not there in current alpine version
## Expected Behaviour

Need ZFS support it works in 5.4.72
 current version is 5.4.52

## Current Behaviour

not able to create zfs files system on disk instead of ext4
## Possible Solution
Need upgraded Alpine OS to kernel version 5.4.72
 then i can install zfs-lts  

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux
* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:
Vagrant and Libvirt 
* Link to your project or a code example to reproduce issue:

**Comment by tstromberg** [comment]
Can anyone confirm if this is still an issue?

**Comment by nshalman** [comment]
> Can anyone confirm if this is still an issue?

I'm pretty sure this is still an issue, and personally I think it would be nice for us to support ZFS.

**Comment by jacobweinstock** [comment]
Archiving repo, closing issue per [GitHub's recommendation](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories#about-repository-archival).
