### ISSUE TITLE
Containerd package gets corrupted sometimes

### ISSUE THREAD

**Issue by invidian** [tinkerbell/osie#183]
## Expected Behaviour

Provisioning OSIE works every time.

## Current Behaviour

Currently, sometimes booting worker with OSIE ends up with no workflow executed. Upon investigation, I figured that cached `containerd` package in OSIE is corrupted and `apk add` is not able to install it, which results in no Docker and no workflows executed.

@gianarb says it's only happening sometimes.

## Steps to Reproduce (for bugs)

1. Provision sandbox repository several times checking if workflow runs each time.

## Context

Discovered while working on https://github.com/tinkerbell/cluster-api-provider-tink/pull/17

## Your Environment

Used OSIE version `https://tinkerbell-oss.s3.amazonaws.com/osie-uploads/osie-v0-n=404,c=c35a5f8,b=master.tar.gz`

Running in sandbox environment using https://github.com/tinkerbell/sandbox/commit/be40a7b371fdab947a413e190cfe99b692651d8e.

**Comment by mmlb** [comment]
Can you try with the last known good version of OSIE, osie-v0-n=466,c=9343abe,b=master?

**Comment by cursedclock** [comment]
I think I've been having a similar issue, osie boots fine but dockerd cannot find containerd executable in PATH. Can you explain how you verified that the cached containerd package is corrupted?

I've had this issue on two different test environments and multiple versions of osie.

Edit: I've noticed if the worker machine is using a virtio nic on qemu it causes containerd on `osie-v0-n=404,c=c35a5f8,b=master` to break.
Switched to `osie-v0-n=466,c=9343abe,b=master` and this still happens but not every time.

**Comment by jacobweinstock** [comment]
Hey @invidian, are you still experiencing this behavior? Were you, by chance, able to try a newer version? Here's one of the latest ones available:

https://tinkerbell-oss.s3.amazonaws.com/osie-uploads/osie-1888-c46887dea61c64a12ac57d8006c0dfafa115bb09.tar.gz

**Comment by invidian** [comment]
Hey @jacobweinstock, I'm sorry, but I won't have time to check if it's still happening. If there is no one else affected, I guess it can be closed.

**Comment by jacobweinstock** [comment]
Sounds good. Will close this then. Thank you!
