### ISSUE TITLE
Docker images fail to download with 'no space left on device' in OSIE

### ISSUE THREAD

**Issue by michael-niemand** [tinkerbell/osie#197]
When trying out the sandbox and using a different workflow than hello world as in the example (I tried https://github.com/alexellis/tinkerbell-ubuntu) the docker images fail to download. I'm posting this here and not in sandbox, because I assume this is rather an issue with the default OSIE (?)

## Expected Behaviour
OSIE environment is able to download necessary Docker images

## Current Behaviour
download of Docker images fails due to 'no space left on device'

## Steps to Reproduce (for bugs)
1. Download and run sandbox
2. Create workflow for https://github.com/alexellis/tinkerbell-ubuntu
3. run the workflow against your hardware
4. tink worker fails with "no space left on device" 

## Context
I noticed the ubuntu installation fails during the first step (wiping the disk), so I checked the docker logs of tink-worker on the machine I'm trying to setup. In the logs it says "no space left on device" when trying to extract the downloaded Docker image. I checked the volumes and the only full volume was /dev/loop0 (/.modloop) with 200MB. 
What am I missing? 

## Your Environment
Using sandbox docker-compose setup on Proxomox VMs with Ubuntu 18.04 LTS as OS

**Comment by mmlb** [comment]
Hey @michael-niemand how much ram is on the machine you're using? OSIE runs from a ramdisk and `/` basically ends up being sized to 1/2 total available ram. That needs to be enough for all of Alpine userland + docker + images + logs. 4G is probably the bare minimum and more than likely right on the edge of usable.

**Comment by michael-niemand** [comment]
thank you for the fast reply, it is very much appreciated! The machine initally had only 2 gig, now I put it to 8 and seems to proceed. Thank you very much.

**Comment by mmlb** [comment]
:+1:
