### ISSUE TITLE
Debug aarch64 vm based power-on/phone-home tests

### ISSUE THREAD

**Issue by mmlb** [tinkerbell/osie#237]
The qemu-system-aarch64 user-mode emulation based boot/phone-home tests from #227 don't work. There's no serial output so its hard to debug atm. Is the test giving up too early? Is something done wrong with qemu? Maybe the aarch64 uefi can't boot from virtio-disks (:thinking:). Need to try the vnc graphical output, maybe there's data there...

## Expected Behaviour

test_boot_and_phone_home works for aarch64 VMs

## Current Behaviour

test_boot_and_phone_home always fails

**Comment by tstromberg** [comment]
Any update?

**Comment by mmlb** [comment]
None, haven't looked into it.

**Comment by jacobweinstock** [comment]
Archiving repo, closing issue per [GitHub's recommendation](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories#about-repository-archival).
