### ISSUE TITLE
Use openRC depend rather than executing "service docker start" from "workflow-helper" script

### ISSUE THREAD

**Issue by invidian** [tinkerbell/osie#24]
https://github.com/OpenRC/openrc/blob/master/service-script-guide.md#the-depend-function

**Comment by RafaelAnsay** [comment]
@invidian @mrmrcoleman  if we want to use openRC depend the right way, i can think of this as a solution:

1. create a docker.rc that will include copying registry certificate (ca.pem) into /etc/docker/....
this docker.rc will eventually replace /etc/init.d/docker in the worker node later.
2. modify all init scripts in osie/installer to add the new rc file and a new rc_add entry
3. modify workflow-helper.rc and add depend(){need docker}
4. modify workflow-helper.sh to remove the starting of docker service and other things.

or do you have any other simpler suggestions? maybe i am missing something.

**Comment by invidian** [comment]
If copying Docker registry certificate is only needed for `workflow-helper.sh`, I think it's fine to keep it in the script, it does not need separate `.rc` file in my opinion. Other than that, the plan sounds good to me. Thanks for looking into it!

**Comment by tstromberg** [comment]
Fixed by https://github.com/tinkerbell/osie/pull/48

**Comment by invidian** [comment]
How is it fixed by #48 when it didn't get merged?

**Comment by tstromberg** [comment]
Woops! I didn't notice that the PR was closed, but not merged. Sorry about that.

**Comment by jacobweinstock** [comment]
Archiving repo, closing issue per [GitHub's recommendation](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories#about-repository-archival).
