### ISSUE TITLE
Log workflow-helper output into the file

### ISSUE THREAD

**Issue by invidian** [tinkerbell/osie#26]
So it can be checked after the execution for investigating.

**Comment by mrmrcoleman** [comment]
@invidian Could you please provide an example of what you're seeing?

**Comment by invidian** [comment]
My idea (and which I used while testing Tinkerbell) was to wrap entire https://github.com/kinvolk/osie/blob/master/installer/workflow-helper.sh script into the function and then pipe it to `/var/log/workflow-helper.log`, so if e.g. fetching CA certificate fails, one can log in onto the machine and check this file for errors.

**Comment by RafaelAnsay** [comment]
Combined PR w/ my other previous PR: https://github.com/tinkerbell/osie/pull/48/files. Now we can find the log in /var/log/workflow-helper.log

**Comment by parauliya** [comment]
Hey @RafaelAnsay , 
Have you tested this with the end to end workflow?

**Comment by gauravgahlot** [comment]
@invidian I believe the issue has been addressed in https://github.com/tinkerbell/osie/pull/48/. So, I'm closing this issue. Please feel free to reopen the issue if otherwise.

**Comment by invidian** [comment]
@gauravgahlot as far as I see #48 has not been merged and I don't see f46c1daaec04cc90e9ecb88a204fe21cefa96855 being added in any other PR. But perhaps this has been addressed someplace else? Do you have any reference to it by any change? Unfortunately, I'm don't have capacity to test latest Tinkerbell if this has been addressed.

Also, if you think this is not important anymore, feel free to keep it closed without fixing it.
