### ISSUE TITLE
Replace osie-build-env with shell.nix

### ISSUE THREAD

**Issue by mmlb** [tinkerbell/osie#3]
osie-build-env is currently used to setup both an developer/build environment and also an environment suitable for running the osie tests. This is done using docker. Instead of (ab)using docker for both scenarios we should instead use `nix` and `nix-shell` for it. With nix-shell we get better support for pinning/choosing tool versions and parity with other tinkerbell/ services dev setups.

The test environment should be completely re-done with either the actual services (with docker-compose.yml or as drone services). This was much harder back in the day pre-cacher, but should be pretty easyish now.

**Comment by alexellis** [comment]
>No description provided.

@mmlb @nathangoulding I'm curious about this change, can you add some context on the what and why?

**Comment by gianarb** [comment]
We would like to get a description in order to prioritize this issue in a better way

**Comment by mmlb** [comment]
Will likely revisit this in the up coming weeks, along with osie's images going from ubuntu:16.04 -> nixos.

**Comment by jacobweinstock** [comment]
Archiving repo, closing issue per [GitHub's recommendation](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories#about-repository-archival).
