### ISSUE TITLE
readme.md link to git-tag-and-release and eng-tools does 404

### ISSUE THREAD

**Issue by fransvanberckel** [tinkerbell/osie#76]
From readme.md: 'Use the git-tag-and-release script found in the eng-tools repo' .... Both links does a 404.

**Comment by displague** [comment]
I also ran into this. The repository does not exist: https://github.com/tinkerbell/eng-tools

**Comment by gianarb** [comment]
We are working on a new release process. That link belongs to an internal tool I think

**Comment by tstromberg** [comment]
Looking at the README, this issue is apparently obsolete.
